language: objective-c
osx_image: xcode7.1
before_install:
- brew update
- brew install mosquitto
script:
- /usr/local/opt/mosquitto/sbin/mosquitto -d
- xcodebuild -project SwiftMQTT/SwiftMQTT.xcodeproj -scheme SwiftMQTT -sdk iphonesimulator test
